# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create(full: "phenylalanine", dna: "ttt", mrna: "uuu")
User.create(full: "phenylalanine", dna: "ttc", mrna: 'uuc')
User.create(full: "leucine", dna: 'tta', mrna: 'uua')
User.create(full: "leucine", dna:"ttg", mrna:"uug")
User.create(full: "leucine", dna:"ctt", mrna:"cuu")
User.create(full: "leucine", dna:"ctc", mrna:"cuc")
User.create(full: "leucine", dna:"cta", mrna:"cua")
User.create(full: "leucine", dna:"ctg", mrna:"cug")
User.create(full: "isoleucine", dna:"att", mrna:"auu")
User.create(full: "isoleucine", dna:"atc", mrna:"auc")
User.create(full: "isoleucine", dna:"ata", mrna:"aua")
User.create(full: "methionine", dna:"atg", mrna:"aug")
User.create(full: "valine", dna:"gtt", mrna:"guu")
User.create(full: "valine", dna:"gtc", mrna:"guc")
User.create(full: "valine", dna:"gta", mrna:"gua")
User.create(full: "valine", dna:"gtg", mrna:"gug")
User.create(full: "serine", dna:"tct", mrna:"ucu")
User.create(full: "serine", dna:"tcc", mrna:"ucc")
User.create(full: "serine", dna:"tca", mrna:"uca")
User.create(full: "serine", dna:"tcg", mrna:"ucg")
User.create(full: "proline", dna:"cct", mrna:"ccu")
User.create(full: "proline", dna:"ccc", mrna:"ccc")
User.create(full: "proline", dna:"cca", mrna:"cca")
User.create(full: "proline", dna:"ccg", mrna:"ccg")
User.create(full: "threonine", dna:"act", mrna:"acu")
User.create(full: "threonine", dna:"acc", mrna:"acc")
User.create(full: "threonine", dna:"aca", mrna:"aca")
User.create(full: "threonine", dna:"acg", mrna:"acg")
User.create(full: "alanine", dna:"gct", mrna:"gcu")
User.create(full: "alanine", dna:"gcc", mrna:"gcc")
User.create(full: "alanine", dna:"gca", mrna:"gca")
User.create(full: "alanine", dna:"gcg", mrna:"gcg")
User.create(full: "tyrosine", dna:"tat", mrna:"uau")
User.create(full: "tyrosine", dna:"tac", mrna:"uac")
User.create(full: "stop", dna:"taa", mrna:"uaa")
User.create(full: "stop", dna:"tag", mrna:"uag")
User.create(full: "histidine", dna:"cat", mrna:"cau")
User.create(full: "histidine", dna:"cac", mrna:"cac")
User.create(full: "glutamine", dna:"cca", mrna:"caa")
User.create(full: "glutamine", dna:"cag", mrna:"cag")
User.create(full: "asparagine", dna:"aat", mrna:"aau")
User.create(full: "asparagine", dna:"aac", mrna:"aac")
User.create(full: "lysine", dna:"aaa", mrna:"aaa")
User.create(full: "lysine", dna:"aag", mrna:"aag")
User.create(full: "aspartic acid", dna:"gat", mrna:"gau")
User.create(full: "aspartic acid", dna:"gac", mrna:"gac")
User.create(full: "glutamic acid", dna:"gaa", mrna:"gaa")
User.create(full: "glutamic acid", dna:"gag", mrna:"gag")
User.create(full: "cysteine", dna:"tgt", mrna:"ugu")
User.create(full: "cysteine", dna:"tgc", mrna:"ugu")
User.create(full: "stop", dna:"tga", mrna:"uga")
User.create(full: "stop", dna:"taa", mrna:"uaa")
User.create(full: "stop", dna:"tag", mrna:"uag")
User.create(full: "tryptophan", dna:"tgg", mrna:"ugg")
User.create(full: "arginine", dna:"cgu", mrna:"cgu")
User.create(full: "arginine", dna:"cgc", mrna:"cgc")
User.create(full: "arginine", dna:"cga", mrna:"cga")
User.create(full: "arginine", dna:"cgg", mrna:"cgg")
User.create(full: "serine", dna:"agt", mrna:"agu")
User.create(full: "serine", dna:"agg", mrna:"agg")
User.create(full: "glycine", dna:"ggt", mrna:"ggu")
User.create(full: "glycine", dna:"gga", mrna:"gga")
User.create(full: "glycine", dna:"ggg", mrna:"ggg")